kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: open-webui
  namespace: app-webui
spec:
  to:
    kind: Service
    name: open-webui
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
