kind: Deployment
apiVersion: apps/v1
metadata:
  name: open-webui
  namespace: app-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
        deployment: open-webui
    spec:
      containers:
        - name: open-webui
          image: "ghcr.io/open-webui/open-webui:main"
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: open-webui
          env:
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data-volume
              mountPath: /app/backend/data
              readOnly: false
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: openwebui-pvc
