kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openwebui-pvc
  namespace: app-webui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
