apiVersion: v1
kind: ConfigMap
metadata:
  name: open-webui
  namespace: app-webui
data:
  WEBUI_AUTH: 'False'
  OPENAI_API_BASE_URLS: 'https://gemma2-llm-serving.apps.rosa.mycluster2.4mbo.p3.openshiftapps.com/v1'
  OPENAI_API_KEYS: na
